# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  resolvers:
    default:
      web_path: ~

  loaders:
    default:
      filesystem:
        data_root:
          - "%kernel.project_dir%/"
          - "%kernel.project_dir%/public/"

  filter_sets:
    cache: ~
    admin_thumb:
      quality: 100
      filters:
        thumbnail: { size: [120, 90], mode: outbound }

    products:
      quality: 100
      filters:
        thumbnail: { size: [500, 500], mode: outbound }