parameters:
    app.database_driver: '%env(DATABASE_DRIVER)%'
    app.database_user: '%env(DATABASE_USER)%'
    app.database_password: '%env(DATABASE_PASSWORD)%'
    app.database_host: '%env(DATABASE_HOST)%'
    app.database_port: '%env(DATABASE_PORT)%'
    app.database_name: '%env(DATABASE_NAME)%'
    app.database_server_version: '%env(DATABASE_VERSION)%'
    app.database_charset: '%env(DATABASE_CHARSET)%'
    app.database_url: '%env(DATABASE_DRIVER)%://%env(DATABASE_USER)%:%env(DATABASE_PASSWORD)%@%env(DATABASE_HOST)%:%env(DATABASE_PORT)%/%env(DATABASE_NAME)%?serverVersion=13&charset=utf8'
    app.mailer_transport: '%env(MAILER_TRANSPORT)%'
    app.mailer_user: '%env(MAILER_USER)%'
    app.mailer_password: '%env(MAILER_PASSWORD)%'
    app.mailer_host: '%env(MAILER_HOST)%'
    app.mailer_port: '%env(MAILER_PORT)%'
    app.mailer_encryption: '%env(MAILER_ENCRYPTION)%'
    app.google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    app.google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    app.secret: '%env(APP_SECRET)%'
    app.lock: '%env(LOCK_DSN)%'
    app.env: '%env(APP_ENV)%'
    app.maintenance: '%env(MAINTENANCE)%'
